using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.Altars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.Altars.Ui;

[GenerateTypedNameReferences]
public sealed partial class AltarMenu : FancyWindow
{
    private string? _currentId;

    private readonly List<AltarPrototype> _cachedPrototypes = new();

    public event Action<string>? OnAltarSelected;

    public AltarMenu(AltarPrototype? currentAltar, List<AltarPrototype> altars)
    {
        RobustXamlLoader.Load(this);
        _currentId = currentAltar?.ID;

        _cachedPrototypes.Clear();
        _cachedPrototypes = altars;
        foreach (var proto in _cachedPrototypes)
        {
            AltarOptions.AddItem(Loc.GetString(proto.Name));
        }

        AltarOptions.OnItemSelected += idx =>
        {
            OnAltarSelected?.Invoke(_cachedPrototypes[idx.Id].ID);
            AltarOptions.SelectId(idx.Id);
        };

        if (currentAltar != null)
        {
            var idx = _cachedPrototypes.IndexOf(currentAltar);
            AltarOptions.TrySelectId(idx);
        }
    }

    public void UpdateState(AltarPrototype newAltar)
    {
        if (_currentId != null && newAltar.ID == _currentId)
            return;
        _currentId = newAltar.ID;
        var idx = _cachedPrototypes.IndexOf(newAltar);
        AltarOptions.TrySelectId(idx);
    }
}
